#!/bin/sh

target=$(date '+%Y-%m-%d')
mkdir -p $target
[ -e latest ] && rm latest
ln -s $target latest

cd $target
exec &> main-log

../receive &> receive-log
(date; echo; cat list | ../filter.rb | ../structure) > formatted 2> structure-log

find . -name '*-log' -size 0 -exec rm {} \;
